<b>General Terms and Condition:</b><br/>
In addition to the above, you are subject to and agree to our general website Termsand Conditions.
Thank you for visiting this website (the “Site” or “website”). Please read the Terms and Conditions contained in this document carefully since any use of this site constitutes your acceptance of the Terms and Conditions set out herein. If you do not agree to these terms and conditions, please do not use this website.
Throughout this site, the terms “we”, “us”, “our”, and “Real Care Pet Adoption” refer to Real Care Pet Adoption, a division of Real Care Small Animal Clinic, Nagpur. “You” refers to any person accessing and/or using this website.

<br/><br/><br/><b>Please Note: These terms and conditions may be revised by Real Care Pet Adoption by updating this posting – Please read them carefully.</b>
<br/><br/>1. Privacy Notice
	Any personal information or material sent to this website are subject to the terms and conditions set out in our Privacy Policy. We encourage you to read and refer to it before you submit any personal information to this Site. The Privacy Policy is a part of these terms and conditions.
<br/><br/>2. Accuracy, completeness and timeliness of information
	We are not responsible if the information that we make available on this website is not accurate or complete. Any reliance upon the material on this website shall be at your own risk. You agree that it is your responsibility to monitor any changes to the material and the information contained on this website.
<br/><br/>3. Submissions to this Site
	Any non-personal communication or material you submit to this website by electronic mail, upload, or otherwise, including any data, questions, comments, suggestions or the like (“Submissions”) are, and will be treated as, non-confidential and non-proprietary. Anything you submit or post becomes the property of Real Care Pet Adoption and Real Care Pet Adoption may use and reproduce such Submission freely, and for any purpose. Specifically, Real Care Pet Adoption is free to use for any purposes whatsoever (including but not limited to the developing, manufacturing, advertising and marketing of products) any ideas, artwork, inventions, developments, suggestions or concepts contained in any Submission you send to this website. Any such use is without compensation to the party submitting information. By making a Submission, you are also warranting that you own the material/content submitted, that it is not defamatory and that Real Care Pet Adoption’s use will not violate any third party’s rights or otherwise place us in breach of any applicable laws. Real Care Pet Adoption is under no obligation to use the information submitted.
<br/><br/>4. Intellectual Property Rights
	All copyright, trademarks and other intellectual property rights in all text, images and other materials on this website are the property of Real Care Pet Adoption or are included with the permission of the relevant owner.
	You are permitted to browse this website, reproduce extracts by way of printing, downloading to a hard disk or for the purposes of distribution to other individuals. This is only to be done on the provision that you keep intact all copyright and other proprietary notices and that the trademark notice below appears on such reproductions. No reproduction of any part of this website may be sold or distributed for commercial gain nor shall it be modified or incorporated in any other work, publication or website.
<br/><br/>5. Links to Other Websites
	Links on the Real Care Pet Adoption websites may take you outside the Real Care Pet Adoption network and systems and Real Care Pet Adoption accepts no responsibility for the content, accuracy or function of these other third party websites. The links are provided in good faith and Real Care Pet Adoption cannot be held responsible for any subsequent change in other third party websites to which we provide a link. The inclusion of any link to other websites does not imply endorsement by Real Care Pet Adoption. We highly recommend that you make yourself aware of and carefully read the legal and privacy notices of all other websites that you visit.
<br/><br/>6. Warranties and Disclaimers
	Your use of this website is at your own and exclusive risk.
<br/><br/>Warranties:
<br/>THIS WEBSITE IS PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS AND, CONSEQUENTLY, REAL CARE PET ADOPTION MAKES NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY OR SATISFACTORY QUALITY AND FITNESS FOR A PARTICULAR PURPOSE) INCLUDING WARRANTIES OR REPRESENTATIONS THAT MATERIAL ON THIS WEBSITE WILL BE COMPLETE, ACCURATE, RELIABLE, TIMELY, NON-INFRINGING TO THIRD PARTIES, THAT ACCESS TO THIS WEBSITE WILL BE UN-INTERRUPTED OR ERROR-FREE OR FREE FROM VIRUSES, THAT THIS WEBSITE WILL BE SECURE, THAT ANY ADVICE OR OPINION OBTAINED FROM REAL CARE PET ADOPTION THROUGH THIS WEBSITE IS ACCURATE OR TO BE RELIED UPON AND ANY REPRESENTATIONS OR WARRANTIES THERETO ARE ACCORDINGLY EXPRESSLY DISCLAIMED.
<br/><br/>Please note that some jurisdictions may not allow exclusions of implied warranties, so some of these exclusions may not apply to you. Please check your local laws.
We reserve the right to restrict, suspend or terminate without notice your access to this website or any feature of this website or any feature or part thereof at any time.
<br/><br/>7. Pet Health, Fitness and Nutrition
	This Site may from time to time contain information relating to nutrition and various medical, health and fitness conditions of pets and their treatment. This is for informational purposes only and is not meant to be a substitute for the advice provided by your own veterinarian or other veterinary professional. You should not use the information contained herein for diagnosing a pet’s health or fitness problem or disease. You should always consult your own veterinarian and/or veterinary advisors.
<br/><br/>8. Limitation of Liability
	Real Care Pet Adoption and/or any other party involved in the creating, producing or delivering this website on our behalf shall have no liability or any responsibility whatsoever for any direct, incidental, consequential, indirect, special or punitive damages, costs, losses or liabilities whatsoever and howsoever arising out of your access to, use, inability to use, change in content of this website or arising from any other website you access through a link from this website or to the extent permitted by applicable law, from any actions we take or fail to take as a result of any electronic mail messages you send us.
	Real Care Pet Adoption shall have no responsibility to maintain the material and services made available on this website or to supply any corrections, updates, or releases in connection therewith. Any material on this website is subject to change without notice.
	Further, Real Care Pet Adoption shall have no liability or any responsibility whatsoever for any loss suffered caused by viruses that may infect your computer equipment or other property by reason of your use of, access to or downloading of any material from this website. If you choose to download material from this website you do so at your own risk.
	Although Real Care Pet Adoption may from time to time monitor or review discussions, chats, postings, transmissions, bulletin boards, and the like on the Site, Real Care Pet Adoption is under no obligation to do so and assumes no responsibility or liability whatsoever arising from the content of any such locations including but not limited to any error, defamation, libel, slander, omission, falsehood, obscenity, pornography, profanity, danger or inaccuracy contained in any information within such locations on the Site.
	To the maximum extent permitted by applicable law, you expressly waive all claims against Real Care Pet Adoption, its officers, directors, employees, suppliers and programmers that may arise from your use or access of this website.
<br/><br/>9. Prohibited Activities
	You are prohibited from doing any act that Real Care Pet Adoption in its absolute discretion may deem to be inappropriate and/or would be deemed to be an unlawful act or is prohibited by any laws applicable to this website including but not limited to:
	<br/><br/>• Any act that would constitute a breach of either the privacy (including uploading private information without the concerned individual’s consent) or any other of the legal rights of individuals
	<br/><br/>• Using this website to defame or libel Real Care Pet Adoption, its employees or other individuals or acting in such a way that brings into disrepute the good name of Real Care Pet Adoption;
	<br/><br/>• Uploading files that contain viruses that may cause damage to the property of Real Care Pet Adoption or the property of other individuals; and
	Posting or transmitting to this website any non-authorized material including but not limited to material that is in our opinion likely to cause annoyance, detrimental to or in violation of Real Care Pet Adoption’s or any third party´s systems or network security, libellous, defamatory, racist, obscene, threatening, pornographic, profane or is otherwise unlawful.
<br/><br/>10. Export Restrictions
	Software from this Site may be further subject to Govt. Of India Export laws, rules and regulations, as amended from time to time. No software from this Site may be downloaded or exported  into any other country.
<br/><br/>11. Mobile Services
	If Real Care Pet Adoption permits or makes available to you the ability to: (a) upload content to the website via your mobile telephone and/or tablet (‘mobile device”), (b) receive and reply to messages, or to access or make posts using text messaging, (c) browse the site from your mobile device or (d) to access features through a mobile application you have downloaded and installed on your mobile device (collectively “Mobile Services”), your mobile carrier’s standard data, Internet, messaging and other service fees and charges apply to your use of, and access to, the Mobile Services, and you are solely responsible for all such fees and charges. The Mobile Services may not be compatible with all mobile devices, carriers, and services, and Real Care Pet Adoption does not make any representations or warranties regarding such compatibility. You are solely responsible for ensuring that your mobile device is compatible with the type of content being provided through the Mobile Services. You understand that content delivered as part of the Mobile Services may be delivered to your device through premium mobile services and acknowledge that you are solely and exclusively responsible for any charges for such services, including but not limited to any roaming charges.
<br/><br/>12. Jurisdiction and governing law
	This website is located in and operated from India. Your use and access to this website will be governed by the laws of theGovt. Of India. 
	You and Real Care Pet Adoption agree that any controversy or claim arising from or pertaining to the use of this website shall be governed by the laws of theState Govt. Of Maharashtra under Govt. Of India, without giving effect to its choice-of-law provisions, and be submitted to the exclusive jurisdiction of the courts of Nagpur, Maharashtra State, India.
<br/><br/>13. Legal notice update
	We reserve the right to make any changes and corrections to this notice. Please refer to this page from time to time to review these and new additional information.
<br/><br/><b>USER GENERATED CONTENT TERMS AND CONDITIONS</b>
	<br/>You accept and agree to the following Terms and conditions for User-Generated Content.
	<br/><b>Eligibility and registration</b>
	<br/>As part of the registration process, you will be asked to select a username and password and you will be responsible for all activities occurring under your username and for keeping your password secure. We may refuse to grant you a username that impersonates someone else, is or may be protected by trademark or proprietary rights law, or is vulgar, offensive or otherwise inappropriate, as determined by us in our sole discretion. You are solely responsible for any and all uses of your username, password, and account.
	Appropriate conduct and content; personal use only User-Generated Websites are made available for your personal, non-commercial use only. User-Generated Websites may not be used for any commercial or promotional purpose.
	By acceptance of these User-Generated Websites Terms and Conditions, you agree that any information you provide about yourself and your pets is accurate and complete information at the time provided. In particular, you represent that you are 18 years of age or older. In addition, you agree to update any information provided to User-Generated Websites to keep it accurate and complete. If you become a member of a User-Generated Website, your failure to accurately and completely provide, and timely update, information about yourself is reasonable grounds for suspension or termination of your membership.
	You may not use User-Generated Websites for any illegal or unauthorized purpose. International users agree to comply with all local rules regarding online conduct and acceptable content, including laws regulating the export of data from the India. You are solely responsible for your conduct and any data, text, information, photos, links and other content (“Materials”) that you submit, post, and display on User-Generated Websites.
	We may without notice to you, but shall have no obligation to, refuse, edit, and/or remove Materials that we determine in our sole discretion are unlawful, fraudulent, threatening, libellous, defamatory, obscene or otherwise objectionable, or infringing or violating any party’s intellectual property or other proprietary rights or these User-Generated Websites Terms and Conditions. We also reserve the right in our sole discretion to refuse, edit, and/or remove any content that may be deemed by any User-Generated Website community to be inappropriate without providing you notice.
	Examples of illegal or unauthorized uses include, but are not limited to:
	Modifying, adapting, translating, or reverse engineering any portion of the User-Generated Websites; using any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of User-Generated Websites; collecting any information about other Members (including usernames and/or e-mail addresses) for unauthorized purposes; reformatting or framing any portion of the web pages or site images that are part of User-Generated Websites; creating user accounts by automated means or under false or fraudulent pretenses; creating or transmitting unwanted electronic communications such as “spam,” or chain letters to other Members or otherwise interfering with other Member’s enjoyment of the service; submitting Materials of any third party without such third party’s prior written consent; submitting Materials that falsely express or imply that such Materials are sponsored or endorsed by User-Generated Websites; submitting Materials that infringe, misappropriate or violate the intellectual property, publicity, privacy or other proprietary rights of any party; transmitting any viruses, worms, defects, Trojan horses or other items of a destructive nature; submitting Materials that are unlawful or promote or encourage illegal activity; displaying an advertisement as part of your or your pet’s profile; any automated use of the system, including the use of scripts to send messages or post comments; or submitting false or misleading information.
	While Real Care Pet Adoption prohibits such conduct and content on its User-Generated Websites, you understand and agree that you nonetheless may be exposed to such Materials and that you use User-Generated Websites at your own risk.
	Changes to Terms and Conditions for User-Generated Content
	We reserve the right to modify or terminate any User-Generated Website or service therein for any reason, and without notice, without liability to you, any other foster, or any third party. We also reserve the right to modify these Terms and Conditions for User-Generated Content from time to time without notice. You are responsible for regularly reviewing these Terms and Conditions for User-Generated Content so that you will be apprised of any changes.
	License to Use Materials
	By submitting, posting, or displaying any Materials on or through User-Generated Websites, you automatically grant Real Care Pet Adoption a worldwide, non-exclusive, royalty-free, irrevocable license to publicly display or re-display such Materials on the User-Generated Websites website and in all other forms of media (including, without limitation, e-mail blasts and mobile or text messages or applications) that are used by Real Care Pet Adoption or its agents in connection with the promotion, marketing, use, or expansion of any User-Generated Websites.
	You represent to Real Care Pet Adoption that you own all Materials you provide and/or have the unencumbered legal right to grant the above-referenced license with respect to all Materials you provide. You further represent to Real Care Pet Adoption that such materials do not infringe any third party copyrights or other third party intellectual property rights. You agree to indemnify Real Care Pet Adoption for any and all loses resulting from the invalidity or inaccuracy of such representation.
	Except as expressly authorized by User-Generated Websites, you may not copy, modify, publish, transmit, distribute, perform, display or sell any of Real Care Pet Adoption’s proprietary information, which includes the sum of all postings and photos to the site.
	Please do not send to any User-Generated Website or post on any User-Generated Website forum anything that constitutes a trade secret, confidential or proprietary information. We are not in a position to accept such information, nor can we agree to obligations of nondisclosure or confidentiality with regard to submitted plans or ideas. You agree that any information or materials that you, or individuals acting on your behalf, provide to any User-Generated Website will not be considered confidential or proprietary.
	User-Generated Websites includes information and content generated from a wide variety of sources, including board certified veterinarians, trainers, and other professional service providers, as well as, other Users. Users should understand that User-Generated Websites is a place to review and share information — but the information has not been verified for accuracy and does not represent the opinions or positions of Real Care Pet Adoption. Real Care Pet Adoption cannot guarantee the timeliness, accuracy, efficacy, or veracity of any information provided at User-Generated Websites, nor the efficiency or applicability of any advice, opinions or content as they may be interpreted and applied to your pet. Real Care Pet Adoption’s personnel are not and will not be responsible for any misleading, false, or otherwise injurious information and advice communicated on User-Generated Websites, or for any results obtained from the use of such information or advice. Real Care Pet Adoption and its personnel will not be liable for any loss or damage suffered by a User through the User’s reliance on information, content and advice appearing on our website.
	 
	<br/><br/><b>USER-GENERATED WEBSITES ARE BEING MADE AVAILABLE TO YOU “AS IS,” WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND.</b>
	<br/>Standard Terms and Conditions for Real Care Pet Adoption Sites
	In addition to these User-Generated Websites Terms and Conditions, you agree to be bound by Real Care Pet Adoption’s standard Terms and Conditions for its websites, as the same may be modified and updated from time to time, with respect to your use of User-Generated Websites.
	
	<br/><br/><b>LINKING POLICY</b>
	<br/>Real Care Pet Adoption grants a nonexclusive, limited permission (“Permission”) to display the Trademarks contained in Real Care Pet Adoption domain names, brand names and logos to the owner(s) of any web sites (“Owner”) that would like to develop a link between their site and the corresponding web site owned by Real Care Pet Adoption (“Real Care Pet Adoption Sites”). The materials on Owner’s site shall not imply any association with or relation to Real Care Pet Adoption or imply in any way that any materials from Real Care Pet Adoption Sites are maintained within Owner’s web site.
	No changes or modifications to the Real Care Pet Adoption domain names, brand names or logos may be made. Use of the Real Care Pet Adoption domain names, brand names or logos for purposes other than linking to Real Care Pet Adoption Sites is expressly forbidden. The domain names, brand names and logos must not be used or associated with any obscene, scandalous, inflammatory, pornographic, indecent, profane, defamatory or unlawful site or materials in any way, or in any manner that would adversely affect the name, reputation and goodwill of Real Care Pet Adoption and its products. Real Care Pet Adoption retains and reserves all rights in and to Real Care Pet Adoption‘s trade names, trademarks, copyrights and all other intellectual property with respect to its domain names, brand names and logos. Real Care Pet Adoption reserves the right to cancel the Permission at any time and for any reason. Upon receipt of such notification, use of the domain names, brand names or logos must cease and the link between the web sites must terminate. Use of Real Care Pet Adoption trademarks, trade names, logos, copyrighted material or any other intellectual property of Real Care Pet Adoption for any purpose not stated herein is expressly forbidden.
	All materials are provided “”AS IS,”” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. Please note that some jurisdictions may not allow the exclusion of implied warranties, so some of the foregoing exclusions may not apply to you. Check your local laws for any restrictions or limitations regarding the exclusion of implied warranties.
	Real Care Pet Adoption shall not be responsible for any loss, damage, liability or expense that may accompany or result from your use of links, domain names, brand names or logos, including but not limited to any computer virus; technical, hardware or software failures of any kind; lost or unavailable network connections; or failed, incomplete, garbled or delayed computer transmissions. The granting of this Permission does not indicate nor should it be construed in any way to represent an endorsement by Real Care Pet Adoption of any materials on a web site containing a Real Care Pet Adoption domain name, brand name or logo or any other Real Care Pet Adoption intellectual property.
	Real Care Pet Adoption may at any time revise this Linking Policy. You are bound by any such revisions and should therefore periodically visit this page to review the then-current Linking Policy to which you are bound.
	The display of Real Care Pet Adoption domain names, brand names and logos on the web site indicates the agreement by the web site Owner to the foregoing terms and conditions.



<br/><br/><b>PRIVACY POLICY</b>

<br/><b>THIS PRIVACY POLICY APPLIES TO OUR SITES, APPS AND OFFLINE ACTIVITIES.</b>
<br/>This Policy describes the types of information we collect from and about you when you visit our websites (each a “site”). This policy also covers our mobile applications (each an “app”) and other interactions with us through other online and offline activities where this policy is provided to you. This policy describes how we use and treat such information. Our sites, apps, and activities are collectively referred to as the “Services.” Throughout this policy, the terms “we”, “us”, “our”, and “Real Care Pet Adoption” refer to Real Care Small Animal Clinic. This includes realcarepet.com. “You” refers to any person accessing and/or using these Services.
This policy applies to our consumer interactions. It does not apply to information collected throughout the application, hiring, or employment process. It does not apply to information collected by our parent company or affiliate companies.
By using our Services you agree to this policy. You also agree to this policy if you otherwise give us your information. This website is subject to Govt. Of India laws, which may not afford the same level of privacy as those in other countries. If you do not agree, please do not use our Services or give us your information. 
WE COLLECT INFORMATION FROM AND ABOUT YOU
Contact information.  The personal information we collect may include your name, postal address, telephone or mobile number, or email address. We may collect this information from third parties.
Account Log-In Information. You may be required to provide information in order to set up an account with us.  We also collect information needed to give you access to your account. This includes your login ID/email address, screen name, and/or password.
Payment information. If you make online purchases, we collect your debit or credit card information.
Demographic and profile information. We may collect information like your gender, age and ethnicity if you fill out an online form or survey. We may collect your zip code. We may collect this information from third parties. For example, we may collect interests you post on social media.
We collect information about your pets and pet preferences. We may collect information when you inquire about adopting a pet through a Real Care Pet Adoption member adoption organization. We may also collect information when you create a saved pet search alert. We may also collect this information when you purchase pet care products from one of our online stores. For example, we might ask what kind of pet you have or the type of pet food you prefer. We collect pet photos you upload to our web sites.
Other Information you may share, submit or post. We may collect information that you post either publicly or on a platform that we provide for sharing among users. We may also collect information that you provide to us through a survey, or otherwise share with us.
We collect information about your browsing preferences, your computer or device, and your Internet usage.  For example, we may collect information about your online behaviour. We may also collect your browser or device type, operating system, or unique device identifier. We may also collect your software version, IP address, and domain name. We may also collect the date and time you visited our site or app. This may include the areas or pages that you visit and the number and duration of visits. It may also include other site usage data and emails that you open, forward, or click-through. We might look at what site you came from, or what site you visit when you leave us, what links you click on, or what pages you view.
We may collect information about your location. This may include your general or precise location. We may collect this using different types of technologies, including GPS and Wi-Fi. If you use our mobile app, we may also access your device’s location information in the background.
WE COLLECT INFORMATION IN DIFFERENT WAYS.
We collect information directly from you. For example, if you create an online account, create a pet search alert, or inquire to adopt a pet. We also collect information if you sign up for newsletters, make an online purchase, or request a coupon. We also collect information if you provide a rating or review, take a survey, fill out an online form, enter a promotion, or otherwise engage with us.
We collect information from you passively. We use tracking tools like browser cookies and web beacons. We also collect information from our mobile apps. Third parties may also collect personal information this way. 

<br/>We get information about you from third parties. We may receive information about you from third parties, which may also include information about your device. For example, social media platforms may give us information about you.
We may combine information. We may combine the information you provide to us with information from other sources. For example, we may combine information that we have collected offline with information we collect online. We may also combine information we get from third parties with information we already have.
WE MAY USE INFORMATION AS DISCLOSED AND DESCRIBED HERE.
We use information to respond to your requests or questions. For example, we might use your information to respond to your customer feedback, inquiries, fulfill orders or otherwise contact and communicate with you. We may use your information to maintain your account or profile. We also may send you a saved pet search alert, or notify you if you win a sweepstakes. We may use your friend’s email address if you give it to us, to share information on adoptable pets, for example.
We use information to communicate with you about your account or our relationship. For example, we may contact you about your account or purchases. We might also contact you about this Policy or our website Terms. We may contact you by mail or email. We may also send push notices.
We use information to improve our products, Services, and business or address problems with the Services or our business. For example, we may use your information to improve our Services, or products. We may also use your information to analyze our products, Services, or sites or our business practices and methods. We may use content you post or share.
We use information for security purposes. We may use information to protect the security or integrity of the Service, our company, and our consumers.
We use information for marketing purposes.  For example, this may include providing you with targeted offers or ads. It may also include providing you with marketing information from us or on behalf of third parties. We may also use your information to tailor ads and messages for you on our sites, apps, and other websites and social platforms. Our marketing may include direct mail and email. It may also include text or social media posts. We may also offer online or digital methods like push notices on our mobile apps.
We use information as otherwise disclosed to you at the point of data collection or as otherwise permitted by law.
WE MAY SHARE INFORMATION WITH THIRD PARTIES.
We may share information with our subsidiaries, parent and affiliated companies in which 
We will share information with third parties who perform services on our behalf. For example, we share information with vendors, such as those that send emails on our behalf or facilitate orders. We may also share information with companies that operate our websites or run promotions.
We will share information with our partners, affiliates, and other third parties. We do this in order to provide you with product, pet adoption, or promotional information. This may include pet adoption organizations to help with an adoption and companies you ask us to share your information with and others. This information may be used by third parties for their own purposes. This may include offers for products or services that may interest you. We may also share anonymous information with third parties for their marketing or analytics uses..
We will share information if we think we have to in order to comply with the law or to protect ourselves. For example, we will share information to respond to a court order or subpoena. We may share it if a government agency or investigatory body requests it. We might also share information when we are investigating potential fraud, claim or dispute against or for us. This might include fraud we think has happened during a sweepstakes or promotion..
We may share information with any successor to all or part of our business.  For example, if part of our business is sold or transferred to a third party, we may give our customer information as part of that transaction.
We may share information for other reasons we may describe to you.
WE USE STANDARD SECURITY MEASURES.
We use standard security measures on our sites and apps. However, the Internet is not 100% secure. We cannot promise that your use of our Services will be completely safe. We encourage you to use caution when using the Internet. This includes not sharing your passwords.
We keep personal information as long as it is necessary or relevant for the practices described in this Policy. We also keep information as otherwise required by law.
WE MAY LINK TO OTHER SITES OR HAVE THIRD PARTY SERVICES ON OUR SITE WE DON’T CONTROL.
If you click on a link to a third party site, you will be taken to websites we do not control. This includes social media sites. This policy does not apply to the privacy practices of these websites. Read the privacy policy of other websites carefully.
We are not responsible for third party practices. Our site may also serve third party ads or other content that contains their own cookies or tracking technologies



<br/>WE MAY UPDATE THIS POLICY.
<br/>From time to time we may change our privacy policies. If we do, we will notify you of any material changes to our Policy as required by law. We will also post an updated copy on our website. Please check our site periodically for updates.
